name: FWSkillableWeapon
version: ${project.version}
main: it.com.FWSkillableWeapon
api-version: 1.16

commands:
  Producer:
  MobExperience:
    description: Change the given experience from mobs
    usage: Syntax error! Simply type /<command> [Monster] [newExperience] change the experience given
